# Generated by Django 3.2.16 on 2022-10-31 07:23

import PDMS.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('top_category', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=22)),
                ('poi', models.FileField(max_length=250, upload_to=PDMS.models.getDirectory, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PDMS.allusers')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(max_length=250, upload_to=PDMS.models.getDirectoryUpload, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDMS.allusers')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_from_user', models.CharField(max_length=150)),
                ('documents', models.FileField(max_length=250, upload_to=PDMS.models.getDirectoryReceived, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDMS.allusers')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=22)),
                ('desc', models.CharField(max_length=200)),
                ('pic1', models.FileField(max_length=250, upload_to=PDMS.models.getDirectory)),
                ('pic2', models.FileField(max_length=250, upload_to=PDMS.models.getDirectory)),
                ('location', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('poi', models.FileField(max_length=250, upload_to=PDMS.models.getDirectory, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PDMS.allusers')),
            ],
        ),
    ]
