# Generated by Django 3.2.16 on 2022-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDMS', '0002_auto_20221128_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
